### ISSUE TITLE
Error after 100th training epoch 

### ISSUE THREAD

**Issue by zendevil** [rkfg/gpt-2#10]
```
[99 | 3832.66] loss=0.5202 avg=1.9767
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1024 is not in [0, 1024)
         [[{{node sample_sequence/while/model/GatherV2_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 221, in <module>
    main()
  File "./train.py", line 188, in main
    generate_samples()
  File "./train.py", line 160, in generate_samples
    feed_dict={context: args.batch_size * [context_tokens]})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1024 is not in [0, 1024)
         [[node sample_sequence/while/model/GatherV2_1 (defined at /home/psharma/gpt-2_fork/src/model.py:157) ]]

Caused by op 'sample_sequence/while/model/GatherV2_1', defined at:
  File "./train.py", line 221, in <module>
    main()
  File "./train.py", line 74, in main
    top_k=40)
  File "/home/psharma/gpt-2_fork/src/sample.py", line 76, in sample_sequence
    back_prop=False,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3525, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/psharma/gpt-2_fork/src/sample.py", line 50, in body
    next_outputs = step(hparams, prev[:, tf.newaxis], past=past)
  File "/home/psharma/gpt-2_fork/src/sample.py", line 33, in step
    lm_output = model.model(hparams=hparams, X=tokens, past=past, reuse=tf.AUTO_REUSE)
  File "/home/psharma/gpt-2_fork/src/model.py", line 157, in model
    h = tf.gather(wte, X) + tf.gather(wpe, positions_for(X, past_length))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 3273, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3748, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[0,0] = 1024 is not in [0, 1024)
         [[node sample_sequence/while/model/GatherV2_1 (defined at /home/psharma/gpt-2_fork/src/model.py:157) ]]
```

**Comment by rkfg** [comment]
Yet again, something's wrong with your data. Maybe you have too small segments (npz arrays), the sampler needs to get 1024 tokens. Add some debug output and try to trace what's going wrong. I trained this network on long books for around 15 days without issues so if something breaks that must be the data or the way you processed it.

**Comment by allo-** [comment]
I get the same, since I upgraded to a version with this commit https://github.com/rkfg/gpt-2/commit/db1784cae78f356e2776439f6e5fa4abccd2cf0a

The change from ``context_tokens = data_sampler.sample(1)`` to ``context_tokens = data_sampler.sample(128)`` introduced the problem.

My ``hparams.json``:

```
{
  "n_vocab": 50000,
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12
}
```
The files are created using the scripts from your repo. The input text size is 410 MB, 145 MB encoded and I trained it successfully for 8000 generations, before I updated the repo.

**Comment by rkfg** [comment]
Interesting. I've never had this error. I don't understand why it happens for you after a while because sampling is random and it's not different from normal training except that for training it samples 1024 tokens and for that output it's only 128. But if setting it to 1 solves this for you, good.

**Comment by allo-** [comment]
For me it happend the first time the new version tried to output a training sample and for the OP probably as well, because the default interval for outputting training samples is every 100 epochs. So I got it at 8100 (starting from 8000) and he got it after the first 100.

I do not see what's wrong, but I would suspect the Sampler object to have some off-by-one error or some similar issue, that does not happen with lenght=1, because then index is always 0. But I did not dig deep enough to be sure about it.
